apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: html
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html 
    spec:
      containers:
      - name: html
        image: systemtesting48/html:latest
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: html 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
    nodePort: 31110
